//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.dataBibia
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class dataBibia { }
#else

	public class dataBibia : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public dataBibia()
		{
			try
			{
				Uri resourceUri = new Uri("/BibiaShow;component/SampleData/dataBibia/dataBibia.xaml", UriKind.RelativeOrAbsolute);
				System.Windows.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Descricao = string.Empty;

		public string Descricao
		{
			get
			{
				return this._Descricao;
			}

			set
			{
				if (this._Descricao != value)
				{
					this._Descricao = value;
					this.OnPropertyChanged("Descricao");
				}
			}
		}

		private System.Windows.Media.ImageSource _Imagem = null;

		public System.Windows.Media.ImageSource Imagem
		{
			get
			{
				return this._Imagem;
			}

			set
			{
				if (this._Imagem != value)
				{
					this._Imagem = value;
					this.OnPropertyChanged("Imagem");
				}
			}
		}

		private double _Sequencia = 0;

		public double Sequencia
		{
			get
			{
				return this._Sequencia;
			}

			set
			{
				if (this._Sequencia != value)
				{
					this._Sequencia = value;
					this.OnPropertyChanged("Sequencia");
				}
			}
		}

		private string _Titulo = string.Empty;

		public string Titulo
		{
			get
			{
				return this._Titulo;
			}

			set
			{
				if (this._Titulo != value)
				{
					this._Titulo = value;
					this.OnPropertyChanged("Titulo");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
